version: '3.7'

volumes:
    prometheus_data: {}

services:
    prometheus:
        image: quay.io/prometheus/prometheus:latest
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus_data:/prometheus
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - 9090:9090
        links:
            - alertmanager
            - node_exporter
    alertmanager:
        image: quay.io/prometheus/alertmanager:latest
        volumes:
            - ./alertmanager:/etc/alertmanager
        ports:
            - 9093:9093
    # not how you should do node_exporter! see prometheus.io ...
    # it's because I work on win+wsl2
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        ports:
            - 9100:9100