global:
  resolve_timeout: 5m
route:
  receiver: default
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
  - receiver: deadmansswitch
    match:
      alertname: DeadMansSwitch
    repeat_interval: 5m
  
receivers:
- name: default
- name: deadmansswitch

templates: []
